### ISSUE TITLE
Crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by libing64** [OGRECave/ogre-meshviewer#12]
Here is the error log when I try to load spider.fbx with ogre-meshviewer. 
[meshviewer-error.log](https://github.com/OGRECave/ogre-meshviewer/files/10527133/meshviewer-error.log)

Can you provide some advice to debug or fix it?

**Comment by libing64** [comment]
Python 3.8.12
ogre-python 13.3.4

**Comment by libing64** [comment]
[spider.zip](https://github.com/OGRECave/ogre-meshviewer/files/10527159/spider.zip)

**Comment by paroj** [comment]
why dont you simply use the snap?
https://snapcraft.io/ogre-meshviewer

in case you wanted to edit the code - this is an issue in combination with the PIP package.
To still use it comment out these lines:
https://github.com/OGRECave/ogre-meshviewer/blob/da9cd55c4f8807791c213c1c5e04f9662617e53d/ogre_mesh_viewer.py#L391

https://github.com/OGRECave/ogre-meshviewer/blob/da9cd55c4f8807791c213c1c5e04f9662617e53d/ogre_mesh_viewer.py#L440

**Comment by libing64** [comment]
@paroj Yes, it works with snap ogre-meshviewer, but I want to use ogre to generate screenshot automatically without manual operation.

**Comment by libing64** [comment]
https://user-images.githubusercontent.com/3192355/215300605-f2d9aa30-e7ff-4b68-88f5-7820a917b417.mp4
