### ISSUE TITLE
Default camera movement is awkward

### ISSUE THREAD

**Issue by sercero** [OGRECave/ogre-meshviewer#18]
Hello,

I find the default movement of the camera not very comfortable.

I would like to implement something more aking to Blender system, what do you think @paroj?

**Comment by paroj** [comment]
it is currently just using OgreBites::CameraMan with CS_ORBIT.

I guess camera controls are somewhat subjective and it is difficult to define a better.

However, feel free to propose something as I am not too attached to the current system. Maybe it makes sense to port it to CameraMan when its done too.

**Comment by sercero** [comment]
I want to implement something similar to Blender which I use for all my projects.

Just wanted to know if you were open to that.
