### ISSUE TITLE
File Open Dialog

### ISSUE THREAD

**Issue by sercero** [OGRECave/ogre-meshviewer#19]
Hello @paroj,

What do you think of implementing a file open dialog?

That way if someone executes `ogre-meshviewer` without passing any command line arguments it is possible to select something after the fact.

I might be able to do it but with some help 😅

**Comment by paroj** [comment]
that is a can of worms actually..

# imgui
there exist multiple implementations using ImGui already:
https://github.com/ocornut/imgui/wiki/Useful-Extensions#file-browsers--file-dialog

each with their own quircks of how to be integrated with the ImGui/ Ogre build.

# native
Then there is something like this:
https://github.com/btzy/nativefiledialog-extended

which delegates to platform code for this. But it needs to be integrated into the Ogre build to be wrapped for python too.

# linux only
on linux, you can just call `zenity --file-selection` - but obviously that will *only* work on Gnome..

**Comment by sercero** [comment]
Ouch, so it seems to be more difficult than I thought.

I'll see what I can do.

**Comment by paroj** [comment]
ah.. if an ugly solution is ok, then this is also an option:
https://stackoverflow.com/a/14119223

**Comment by sercero** [comment]
> ah.. if an ugly solution is ok, then this is also an option: https://stackoverflow.com/a/14119223

That might be the best solution, if ugly because all the FileOpenDialog options for ImGui require C++
