### ISSUE TITLE
facing an error while running batch file

### ISSUE THREAD

**Issue by waseemkhan1989** [OGRECave/ogre-meshviewer#3]
Hi,
I downloaded windows portable package of ogre-meshviewer and tried to run batch file with command
"ogre-meshviewer  part.mesh" (part.mesh is the file that I want to visualize). I am assuming that all the dependencies like ogre 1.11.5+,ogre-imgui and python3 are already met within this package. But I am facing an error and corresponding screenshot is attached for your perusal. I am using Microsoft Windows 8.1.
![screenshot](https://user-images.githubusercontent.com/25552247/54087481-6fe2ec80-4353-11e9-84eb-4ea251c5c612.png)

Could you resolve this issue?

**Comment by paroj** [comment]
the app is working correctly, but your mesh file seems to be corrupt, please test with:
https://github.com/OGRECave/ogre/raw/master/Samples/Media/models/ogrehead.mesh

also please copy & paste the error log in textual form instead of making a screenshot.

**Comment by waseemkhan1989** [comment]
> the app is working correctly, but your mesh file seems to be corrupt, please test with:
> https://github.com/OGRECave/ogre/raw/master/Samples/Media/models/ogrehead.mesh
> 
> also please copy & paste the error log in textual form instead of making a screenshot.

My apologies! I would be careful next time. 
Thanks for your reply and for the mesh file.  It worked with your file. May be , there was some issue with my file. Many thanks once again.
