### ISSUE TITLE
Installing meshviewer through files available in git repository

### ISSUE THREAD

**Issue by waseemkhan1989** [OGRECave/ogre-meshviewer#4]
Hi,

Another issue is that if I don't want to use Windows portable package and want to have a working meshviewer through downloading git repository then what are the steps that I should follow to be able to have a working meshviewer? I don't understand how could I connect all its dependencies(like ogre-imgui, ogre 1.11.5+ and python) to run meshviewer?
Thanks.

**Comment by paroj** [comment]
currently you have to manually copy everything together like is shown in the portable package

**Comment by waseemkhan1989** [comment]
> currently you have to manually copy everything together like is shown in the portable package

Thank you so much:)
