### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fegorsch** [OGRECave/ogre-meshviewer#6]
After being left open for the weekend the meshviewer needed about 7.5 GB memory. I only had a simple box geometry loaded. There's probably a small memory leak somewhere.

**Comment by paroj** [comment]
might be in the SWIG generated glue code. Please run it through Valgrind to find out more.

**Comment by paroj** [comment]
running ASAN on the current master of everything does not show anything suspicious.

there are some leaks of singleton objects, which is ok.
howver, it might be even python itself leaking - which sums up if you have callbacks at 60fps:
https://bugs.python.org/issue35774

closing as incomplete as there is nothing that I can do about it
