### ISSUE TITLE
Empty material name encountered

### ISSUE THREAD

**Issue by yangjituan** [OGRECave/ogre-meshviewer#8]
Hi, i just run into a problem "Error: empty material name encountered" when i try to open a mesh file, just like below:
![image](https://user-images.githubusercontent.com/53220351/102178611-a9f60080-3ee0-11eb-8548-645b6a82afc6.png)
The files is from a mayaOgreExporter. 
can you help me to solve it? or give me some useful information,
Thanks very much!

**Comment by paroj** [comment]
this means the material name inside the mesh is wrong, which is a problem with the exporter. Tried to clarify the message in:
https://github.com/OGRECave/ogre-meshviewer/commit/726a1a0d6a0703aefe40113dcfb82a3994e18d41
