### ISSUE TITLE
tried loading different kinds of meshes, results in the same error...

### ISSUE THREAD

**Issue by celadaris** [OGRECave/ogre-meshviewer#9]
System Error: The specified module could not be found. in DynLib::load at C:\projects\ogre-bsrh7\OgreMain\src\OgreDynLib.cpp (line 117)

![Capture](https://user-images.githubusercontent.com/12479149/103452561-8085f480-4c96-11eb-9066-fc7103b948e2.PNG)

**Comment by celadaris** [comment]
was I supposed to have something pre-installed for it to work?

**Comment by paroj** [comment]
try deleting `C:/Users/Carmen/Documents/OgreMeshViewer/ogre.cfg` and selecting the GL RenderSystem.
For D3D9 you might need:
https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by celadaris** [comment]
Thanks! it worked! 💯
